# Generated by Django 4.1.1 on 2022-09-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0002_auto_20191219_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorlist',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='donorlist',
            name='any_diseases',
        ),
        migrations.RemoveField(
            model_name='donorlist',
            name='bleeding_disorders',
        ),
        migrations.RemoveField(
            model_name='donorlist',
            name='cardiac',
        ),
        migrations.RemoveField(
            model_name='donorlist',
            name='hbsAg_hcv_hIV',
        ),
        migrations.RemoveField(
            model_name='donorlist',
            name='home_address',
        ),
        migrations.AddField(
            model_name='donorlist',
            name='Current_City',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
