# Generated by Django 4.1.1 on 2022-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0003_remove_donorlist_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorlist',
            name='Current_City',
            field=models.TextField(blank=True, null=True),
        ),
    ]
